name: Test Configuration Server

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/quarkus-testing-java.yml'
      - 'quarkus-*/**'
      - '!*.md'
      - '!**/*.md'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/quarkus-testing-java.yml'
      - 'quarkus-*/**'
      - '!*.md'
      - '!**/*.md'
jobs:
  test:
    name: build and test all examples
    runs-on: ubuntu-latest
    container: openjdk:11-jdk
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: quarkus-jpa-java
      - name: quarkus-jpa-java
        run: ./gradlew clean assemble test
        working-directory: quarkus-jpa-java
