name: Build and test all examples

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/quarkus-testing-java.yml'
      - 'quarkus-*/**'
      - '!*.md'
      - '!**/*.md'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/quarkus-testing-java.yml'
      - 'quarkus-*/**'
      - '!*.md'
      - '!**/*.md'
jobs:
  test:
    name: build and test all examples
    runs-on: ubuntu-latest
    container: openjdk:11-jdk
    strategy:
      fail-fast: false
      matrix:
        working-dir:
          - 'quarkus-jpa-java'
          - 'quarkus-mongodb-java'
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ matrix.working-dir }}
      - name: clean assemble test ${{ matrix.working-dir }}
        run: ./gradlew clean assemble test
        working-directory: ${{ matrix.working-dir }}
